### ISSUE TITLE
error running predictions.py

### ISSUE THREAD

**Issue by REALLMOD** [mhaythornthwaite/Football_Prediction_Project#8]
how to solve this error

Traceback (most recent call last):
  File "predictions/predictions.py", line 168, in <module>
    clf = pickle.load(open(f'{path_to_model}', 'rb'))
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\__init__.py", line 80, in <module>
    from .base import clone
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    import scipy.stats
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\stats\__init__.py", line 367, in <module>
    from .stats import *
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\stats\stats.py", line 172, in <module>
    import scipy.special as special
  File "C:\Users\OWNER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.

Here is all the package installed

Package            Version
------------------ ------------
certifi            2023.11.17
chardet            3.0.4
click              8.1.7
colorama           0.4.6
cycler             0.11.0
Flask              1.1.2
fonttools          4.38.0
idna               2.10
importlib-metadata 6.7.0
itsdangerous       2.1.2
Jinja2             3.1.2
joblib             1.3.2
kiwisolver         1.4.5
MarkupSafe         2.1.3
matplotlib         3.2.2
numpy              1.18.5
packaging          23.2
pandas             1.0.5
pickleshare        0.7.5
Pillow             9.5.0
pyparsing          3.1.1
python-dateutil    2.8.2
pytz               2023.3.post1
requests           2.24.0
scikit-learn       0.23.1
scipy              1.2.1
seaborn            0.10.1
six                1.16.0
threadpoolctl      3.1.0
typing-extensions  4.7.1
urllib3            1.25.11
Werkzeug           2.2.3
zipp               3.15.0

**Comment by mhaythornthwaite** [comment]
Your error is occuring in the following line: 
```
File "predictions/predictions.py", line 168, in
clf = pickle.load(open(f'{path_to_model}', 'rb'))
```
Note that this line of code is loading a trained model that has been saved from one of the ml_model_build scripts. Please check the path you are feeding into line 168 correctly points to one of these models.
